Parameters:
  NameOfService:
    Description: "The Name of the service this stack is to be used for"
    Type: String
  
  InstanceTypeParameter:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - m1.small
      - m1.large

  KeyName:
    Description: Name of ec2 login key
    Type: AWS::EC2::KeyPair::KeyName

Mappings: 
  AMIRegionMap: 
    us-east-2: 
      AMI: ami-07f463d9d4a6f005f
    us-west-1: 
      AMI: ami-03392a27e4a01f1e4
    us-west-2: 
      AMI: ami-00c257e12d6828491

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              php: []
              httpd: []
              wget: []
              unzip: []
              git: []
          commands:
            test:
              command: "wget https://www.tooplate.com/zip-templates/2119_gymso_fitness.zip && unzip 2119_gymso_fitness.zip && cp -r 2119_gymso_fitness/* /var/www/html/"
          files:
            /var/www/html/hello.html:
              content: !Sub |
                <DOCTYPE html>
                <html>
                <body>
                <h1>Welcome to Cloudformation.</h1>
                <p>This site is deployed by Cloudformation.</p>
                <body>
                <html>
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AMIRegionMap
        - !Ref AWS::Region
        - AMI 
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
      SecurityGroups:
        - !Ref VprofileSG
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash -xe
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}
  
  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http from myIp
      GroupName: VprofileSG

      SecurityGroupIngress: 
        - Description: Inbound rule for http
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80

        - Description: Inbound rule for ssh
          IpProtocol: tcp
          CidrIp: 223.123.15.49/32
          FromPort: 22
          ToPort: 22

Outputs:
  PrintSomeInfo:
    Value: !GetAtt 
      - MyInstance
      - PublicDnsName  
